ubuntu@ip-172-31-31-7:~$ /bin/python3 "/home/ubuntu/NOSQL_MONGODBEXPRESS/from pymongo import MongoClient.py"
la liste des bases de données est : ['TEST', 'admin', 'config', 'local', 'sample']


la liste des collections est : ['zips', 'books']


un exemple au hasard de livre est :
{'_id': 1,
 'authors': ['W. Frank Ableson', 'Charlie Collins', 'Robi Sen'],
 'categories': ['Open Source', 'Mobile'],
 'isbn': '1933988673',
 'longDescription': 'Android is an open source mobile phone platform based on '
                    'the Linux operating system and developed by the Open '
                    'Handset Alliance, a consortium of over 30 hardware, '
                    'software and telecom companies that focus on open '
                    'standards for mobile devices. Led by search giant, '
                    'Google, Android is designed to deliver a better and more '
                    'open and cost effective mobile experience.    Unlocking '
                    "Android: A Developer's Guide provides concise, hands-on "
                    'instruction for the Android operating system and '
                    'development tools. This book teaches important '
                    'architectural concepts in a straightforward writing style '
                    'and builds on this with practical and useful examples '
                    'throughout. Based on his mobile development experience '
                    'and his deep knowledge of the arcane Android technical '
                    'documentation, the author conveys the know-how you need '
                    'to develop practical applications that build upon or '
                    'replace any of Androids features, however small.    '
                    "Unlocking Android: A Developer's Guide prepares the "
                    'reader to embrace the platform in easy-to-understand '
                    'language and builds on this foundation with re-usable '
                    'Java code examples. It is ideal for corporate and '
                    'hobbyists alike who have an interest, or a mandate, to '
                    "deliver software functionality for cell phones.    WHAT'S "
                    "INSIDE:        * Android's place in the market      * "
                    'Using the Eclipse environment for Android '
                    'development      * The Intents - how and why they are '
                    'used      * Application classes:            o '
                    'Activity            o Service            o '
                    'IntentReceiver       * User interface design      * Using '
                    'the ContentProvider to manage data      * Persisting data '
                    'with the SQLite database      * Networking examples      '
                    '* Telephony applications      * Notification methods      '
                    '* OpenGL, animation & multimedia      * Sample '
                    'Applications  ',
 'pageCount': 416,
 'publishedDate': datetime.datetime(2009, 4, 1, 7, 0),
 'shortDescription': "Unlocking Android: A Developer's Guide provides concise, "
                     'hands-on instruction for the Android operating system '
                     'and development tools. This book teaches important '
                     'architectural concepts in a straightforward writing '
                     'style and builds on this with practical and useful '
                     'examples throughout.',
 'status': 'PUBLISH',
 'thumbnailUrl': 'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson.jpg',
 'title': 'Unlocking Android'}


un 2ème exemple correspondant à l'id 2 de livre est :
[{'_id': 2,
  'authors': ['W. Frank Ableson', 'Robi Sen'],
  'categories': ['Java'],
  'isbn': '1935182722',
  'longDescription': 'When it comes to mobile apps, Android can do almost '
                     'anything   and with this book, so can you! Android runs '
                     'on mobile devices ranging from smart phones to tablets '
                     "to countless special-purpose gadgets. It's the broadest "
                     'mobile platform available.    Android in Action, Second '
                     'Edition is a comprehensive tutorial for Android '
                     'developers. Taking you far beyond "Hello Android," this '
                     "fast-paced book puts you in the driver's seat as you "
                     'learn important architectural concepts and '
                     "implementation strategies. You'll master the SDK, build "
                     'WebKit apps using HTML 5, and even learn to extend or '
                     "replace Android's built-in features by building useful "
                     'and intriguing examples. ',
  'pageCount': 592,
  'publishedDate': datetime.datetime(2011, 1, 14, 8, 0),
  'shortDescription': 'Android in Action, Second Edition is a comprehensive '
                      'tutorial for Android developers. Taking you far beyond '
                      '"Hello Android," this fast-paced book puts you in the '
                      "driver's seat as you learn important architectural "
                      "concepts and implementation strategies. You'll master "
                      'the SDK, build WebKit apps using HTML 5, and even learn '
                      "to extend or replace Android's built-in features by "
                      'building useful and intriguing examples. ',
  'status': 'PUBLISH',
  'thumbnailUrl': 'https://s3.amazonaws.com/AKIAJC5RLADLUMVRPFDQ.book-thumb-images/ableson2.jpg',
  'title': 'Android in Action, Second Edition'}]


le nombre de documents de la collection est : 431


le nombre de livres de plus de 400 pages est : 157


le nombre de livres de plus de 400 pages publiés est : 155


le nombre de livres où Android est présent dans une des descriptions est :  4


les modalités du 1er élément des catégories sont :
['Algorithmic Art',
 'Business',
 'Client-Server',
 'Computer Graphics',
 'In Action',
 'Internet',
 'Java',
 'Microsoft',
 'Microsoft .NET',
 'Microsoft/.NET',
 'Miscellaneous',
 'Mobile Technology',
 'Networking',
 'Next Generation Databases',
 'Object-Oriented Programming',
 'Object-Technology Programming',
 'Open Source',
 'PHP',
 'Perl',
 'PowerBuilder',
 'Programming',
 'Python',
 'SOA',
 'Software Engineering',
 'Theory',
 'Web Development',
 'XML',
 'internet',
 'java']


les modalités du 2ème élément des catégories sont :
[{'_id': 'Mobile'},
 {'_id': ''},
 {'_id': 'Java'},
 {'_id': 'Python'},
 {'_id': 'Business'},
 {'_id': None},
 {'_id': 'Computer Graphics'},
 {'_id': 'Theory'},
 {'_id': 'Client-Server'},
 {'_id': 'P'},
 {'_id': 'Open Source'},
 {'_id': 'Networking'},
 {'_id': '.NET'},
 {'_id': 'Perl'},
 {'_id': 'Software Development'},
 {'_id': 'Internet'},
 {'_id': 'Software Engineering'},
 {'_id': 'S'}]


le nombre de livre contenant les mots-clefs Python, Java, C++, Scala et Python dans leur description longue :  126


les statistiques relatives aux pages des livres par catégorie sont :
[{'_id': ['Business'], 'max_pages': 528, 'min_pages': 236, 'moy_pages': 406.0},
 {'_id': ['Software Engineering'],
  'max_pages': 544,
  'min_pages': 0,
  'moy_pages': 236.16666666666666},
 {'_id': ['PowerBuilder'],
  'max_pages': 504,
  'min_pages': 362,
  'moy_pages': 414.3333333333333},
 {'_id': ['Java', 'Computer Graphics'],
  'max_pages': 520,
  'min_pages': 520,
  'moy_pages': 520.0},
 {'_id': ['Networking', 'Theory'],
  'max_pages': 591,
  'min_pages': 591,
  'moy_pages': 591.0},
 {'_id': ['Microsoft'], 'max_pages': 700, 'min_pages': 344, 'moy_pages': 522.0},
 {'_id': ['Java', 'Software Engineering'],
  'max_pages': 432,
  'min_pages': 432,
  'moy_pages': 432.0},
 {'_id': ['Java', 'Software Development'],
  'max_pages': 600,
  'min_pages': 600,
  'moy_pages': 600.0},
 {'_id': ['Internet', 'Java'],
  'max_pages': 632,
  'min_pages': 402,
  'moy_pages': 517.0},
 {'_id': ['Java', 'Open Source'],
  'max_pages': 532,
  'min_pages': 532,
  'moy_pages': 532.0},
 {'_id': ['Networking'],
  'max_pages': 420,
  'min_pages': 420,
  'moy_pages': 420.0},
 {'_id': ['Web Development'],
  'max_pages': 688,
  'min_pages': 300,
  'moy_pages': 441.47058823529414},
 {'_id': ['Internet', 'Networking'],
  'max_pages': 341,
  'min_pages': 341,
  'moy_pages': 341.0},
 {'_id': ['Python'], 'max_pages': 688, 'min_pages': 350, 'moy_pages': 492.4},
 {'_id': ['Object-Technology Programming', ''],
  'max_pages': 200,
  'min_pages': 200,
  'moy_pages': 200.0},
 {'_id': ['internet'], 'max_pages': 400, 'min_pages': 400, 'moy_pages': 400.0},
 {'_id': ['Miscellaneous'],
  'max_pages': 1096,
  'min_pages': 316,
  'moy_pages': 706.0},
 {'_id': ['Internet', 'Theory', 'XML'],
  'max_pages': 304,
  'min_pages': 304,
  'moy_pages': 304.0},
 {'_id': ['Internet', 'Theory'],
  'max_pages': 450,
  'min_pages': 450,
  'moy_pages': 450.0},
 {'_id': ['Computer Graphics'],
  'max_pages': 840,
  'min_pages': 400,
  'moy_pages': 568.5},
 {'_id': ['Theory'], 'max_pages': 330, 'min_pages': 280, 'moy_pages': 305.0},
 {'_id': ['Computer Graphics', 'Perl'],
  'max_pages': 328,
  'min_pages': 328,
  'moy_pages': 328.0},
 {'_id': ['Open Source', 'Mobile'],
  'max_pages': 416,
  'min_pages': 416,
  'moy_pages': 416.0},
 {'_id': ['Business', 'Client-Server'],
  'max_pages': 696,
  'min_pages': 220,
  'moy_pages': 505.3333333333333},
 {'_id': ['Java', 'Client-Server', 'Internet'],
  'max_pages': 592,
  'min_pages': 592,
  'moy_pages': 592.0},
 {'_id': ['Java', 'Business', 'Client Server', ''],
  'max_pages': 368,
  'min_pages': 368,
  'moy_pages': 368.0},
 {'_id': ['Software Engineering', 'Theory'],
  'max_pages': 540,
  'min_pages': 448,
  'moy_pages': 494.0},
 {'_id': ['Perl', 'Client-Server'],
  'max_pages': 424,
  'min_pages': 424,
  'moy_pages': 424.0},
 {'_id': ['Programming'],
  'max_pages': 570,
  'min_pages': 0,
  'moy_pages': 355.8181818181818},
 {'_id': ['java'], 'max_pages': 0, 'min_pages': 0, 'moy_pages': 0.0},
 {'_id': ['Internet', 'Networking', 'Miscella'],
  'max_pages': 0,
  'min_pages': 0,
  'moy_pages': 0.0},
 {'_id': ['Client-Server'],
  'max_pages': 1101,
  'min_pages': 280,
  'moy_pages': 690.5},
 {'_id': ['Algorithmic Art'], 'max_pages': 0, 'min_pages': 0, 'moy_pages': 0.0},
 {'_id': ['Java', 'Business'],
  'max_pages': 180,
  'min_pages': 180,
  'moy_pages': 180.0},
 {'_id': ['Microsoft .NET'],
  'max_pages': 848,
  'min_pages': 0,
  'moy_pages': 439.3636363636364},
 {'_id': ['Object-Oriented Programming', 'P'],
  'max_pages': 512,
  'min_pages': 512,
  'moy_pages': 512.0},
 {'_id': ['Microsoft/.NET'], 'max_pages': 0, 'min_pages': 0, 'moy_pages': 0.0},
 {'_id': ['PHP'], 'max_pages': 552, 'min_pages': 552, 'moy_pages': 552.0},
 {'_id': ['PowerBuilder', 'Client-Server'],
  'max_pages': 550,
  'min_pages': 550,
  'moy_pages': 550.0},
 {'_id': ['Mobile Technology'],
  'max_pages': 504,
  'min_pages': 0,
  'moy_pages': 296.5},
 {'_id': ['XML', 'Java'],
  'max_pages': 624,
  'min_pages': 624,
  'moy_pages': 624.0},
 {'_id': ['XML', 'Internet'],
  'max_pages': 680,
  'min_pages': 320,
  'moy_pages': 500.0},
 {'_id': ['Programming', 'Python'],
  'max_pages': 432,
  'min_pages': 432,
  'moy_pages': 432.0},
 {'_id': ['Java', 'Internet', 'Computer Graph'],
  'max_pages': 400,
  'min_pages': 400,
  'moy_pages': 400.0},
 {'_id': ['Business', 'Software Engineering'],
  'max_pages': 350,
  'min_pages': 350,
  'moy_pages': 350.0},
 {'_id': ['SOA'], 'max_pages': 250, 'min_pages': 250, 'moy_pages': 250.0},
 {'_id': ['In Action'], 'max_pages': 0, 'min_pages': 0, 'moy_pages': 0.0},
 {'_id': ['Java'],
  'max_pages': 1088,
  'min_pages': 0,
  'moy_pages': 380.2236842105263},
 {'_id': ['Next Generation Databases'],
  'max_pages': 0,
  'min_pages': 0,
  'moy_pages': 0.0},
 {'_id': ['Client-Server', 'Networking'],
  'max_pages': 543,
  'min_pages': 320,
  'moy_pages': 404.3333333333333},
 {'_id': ['Internet'],
  'max_pages': 600,
  'min_pages': 200,
  'moy_pages': 391.23809523809524},
 {'_id': ['Object-Oriented Programming', 'S'],
  'max_pages': 350,
  'min_pages': 350,
  'moy_pages': 350.0},
 {'_id': ['Perl'], 'max_pages': 504, 'min_pages': 304, 'moy_pages': 390.0},
 {'_id': ['Java', 'Internet'],
  'max_pages': 912,
  'min_pages': 408,
  'moy_pages': 599.3333333333334},
 {'_id': [], 'max_pages': 950, 'min_pages': 0, 'moy_pages': 90.2},
 {'_id': ['Microsoft', '.NET'],
  'max_pages': 925,
  'min_pages': 925,
  'moy_pages': 925.0},
 {'_id': ['Object-Oriented Programming'],
  'max_pages': 420,
  'min_pages': 352,
  'moy_pages': 386.0},
 {'_id': ['Microsoft .NET', 'Internet'],
  'max_pages': 360,
  'min_pages': 360,
  'moy_pages': 360.0}]


les dates de publication avec annee, mois et jour dans des colonnes separees sont :
[{'day': 1, 'month': 4, 'year': 2009},
 {'day': 14, 'month': 1, 'year': 2011},
 {'day': 3, 'month': 6, 'year': 2011},
 {'day': 15, 'month': 11, 'year': 2010},
 {'day': 2, 'month': 2, 'year': 2009},
 {'day': 15, 'month': 10, 'year': 2010},
 {'day': 4, 'month': 6, 'year': 2012},
 {'day': 12, 'month': 12, 'year': 2011},
 {'day': 1, 'month': 11, 'year': 2009},
 {'day': 12, 'month': 12, 'year': 2011},
 {'day': 16, 'month': 4, 'year': 2010},
 {'day': 1, 'month': 6, 'year': 2010},
 {'day': 1, 'month': 4, 'year': 2009},
 {'day': 1, 'month': 10, 'year': 2009},
 {'day': 15, 'month': 5, 'year': 2011},
 {'day': 13, 'month': 2, 'year': 2012},
 {'day': 1, 'month': 11, 'year': 2013},
 {'day': 1, 'month': 1, 'year': 2010},
 {'day': 4, 'month': 9, 'year': 2010},
 {'day': 1, 'month': 8, 'year': 2009},
 {'day': 30, 'month': 9, 'year': 2011},
 {'day': 17, 'month': 10, 'year': 2012},
 {'day': 1, 'month': 5, 'year': 2009},
 {'day': 13, 'month': 4, 'year': 2012},
 {'day': 27, 'month': 7, 'year': 2012},
 {'day': 1, 'month': 7, 'year': 2009},
 {'day': 1, 'month': 5, 'year': 2009},
 {'day': 6, 'month': 4, 'year': 2011},
 {'day': 13, 'month': 2, 'year': 2012},
 {'day': 9, 'month': 7, 'year': 2010},
 {'day': 22, 'month': 10, 'year': 2010},
 {'day': 31, 'month': 12, 'year': 2012},
 {'day': 20, 'month': 8, 'year': 2011},
 {'day': 4, 'month': 1, 'year': 2011},
 {'day': 1, 'month': 1, 'year': 2009},
 {'day': 31, 'month': 12, 'year': 2012},
 {'day': 1, 'month': 8, 'year': 2009},
 {'day': 9, 'month': 6, 'year': 2011},
 {'day': 15, 'month': 4, 'year': 2011},
 {'day': 15, 'month': 8, 'year': 2011},
 {'day': 20, 'month': 9, 'year': 2011},
 {'day': 14, 'month': 3, 'year': 2011},
 {'day': 4, 'month': 2, 'year': 2013},
 {'day': 19, 'month': 9, 'year': 2013},
 {'day': 1, 'month': 2, 'year': 2009},
 {'day': 1, 'month': 9, 'year': 2009},
 {'day': 1, 'month': 12, 'year': 2010},
 {'day': 12, 'month': 2, 'year': 2011},
 {'day': 11, 'month': 4, 'year': 2012},
 {'day': 16, 'month': 11, 'year': 2010},
 {'day': 9, 'month': 9, 'year': 2009},
 {'day': 26, 'month': 9, 'year': 2012},
 {'day': 22, 'month': 11, 'year': 2010},
 {'day': 29, 'month': 5, 'year': 2009},
 {'day': 1, 'month': 12, 'year': 2011},
 {'day': 1, 'month': 3, 'year': 2009},
 {'day': 1, 'month': 10, 'year': 2009},
 {'day': 1, 'month': 5, 'year': 2011},
 {'day': 26, 'month': 7, 'year': 2013},
 {'day': 1, 'month': 11, 'year': 2009},
 {'day': 15, 'month': 11, 'year': 2009},
 {'day': 1, 'month': 11, 'year': 2009},
 {'day': 11, 'month': 4, 'year': 2011},
 {'day': 1, 'month': 5, 'year': 2009},
 {'day': 5, 'month': 10, 'year': 2011},
 {'day': 1, 'month': 9, 'year': 2009},
 {'day': 1, 'month': 6, 'year': 2010},
 {'day': 25, 'month': 5, 'year': 2012},
 {'day': 7, 'month': 4, 'year': 2014},
 {'day': 15, 'month': 5, 'year': 2011},
 {'day': 1, 'month': 6, 'year': 2012},
 {'day': 4, 'month': 10, 'year': 2010},
 {'day': 30, 'month': 6, 'year': 2011},
 {'day': 21, 'month': 8, 'year': 2012},
 {'day': 18, 'month': 11, 'year': 2011},
 {'day': 1, 'month': 12, 'year': 2009},
 {'day': 1, 'month': 8, 'year': 2009},
 {'day': 4, 'month': 4, 'year': 2012},
 {'day': 12, 'month': 7, 'year': 2012},
 {'day': 1, 'month': 1, 'year': 2010},
 {'day': 9, 'month': 4, 'year': 2013},
 {'day': 15, 'month': 11, 'year': 2011},
 {'day': 27, 'month': 12, 'year': 2012},
 {'day': 22, 'month': 11, 'year': 2010},
 {'day': 1, 'month': 3, 'year': 2009},
 {'day': 12, 'month': 9, 'year': 2012},
 {'day': 16, 'month': 9, 'year': 2011},
 {'day': 14, 'month': 11, 'year': 2011},
 {'day': 3, 'month': 10, 'year': 2011},
 {'day': 20, 'month': 9, 'year': 2011},
 {'day': 8, 'month': 6, 'year': 2010},
 {'day': 30, 'month': 4, 'year': 2012},
 {'day': 1, 'month': 5, 'year': 2009},
 {'day': 31, 'month': 3, 'year': 2011},
 {'day': 9, 'month': 5, 'year': 2011},
 {'day': 14, 'month': 5, 'year': 2012},
 {'day': 21, 'month': 1, 'year': 2013},
 {'day': 1, 'month': 7, 'year': 2010},
 {'day': 1, 'month': 10, 'year': 2011},
 {'day': 1, 'month': 8, 'year': 2010},
 {'day': 20, 'month': 4, 'year': 2012},
 {'day': 9, 'month': 5, 'year': 2013},
 {'day': 21, 'month': 6, 'year': 2011},
 {'day': 7, 'month': 2, 'year': 2011},
 {'day': 24, 'month': 4, 'year': 2011},
 {'day': 24, 'month': 2, 'year': 2012},
 {'day': 4, 'month': 2, 'year': 2014},
 {'day': 15, 'month': 11, 'year': 2011},
 {'day': 30, 'month': 5, 'year': 2013},
 {'day': 15, 'month': 10, 'year': 2013},
 {'day': 11, 'month': 3, 'year': 2013},
 {'day': 9, 'month': 5, 'year': 2014},
 {'day': 13, 'month': 10, 'year': 2011},
 {'day': 10, 'month': 2, 'year': 2014},
 {'day': 2, 'month': 10, 'year': 2012},
 {'day': 30, 'month': 5, 'year': 2012},
 {'day': 2, 'month': 11, 'year': 2012},
 {'day': 30, 'month': 11, 'year': 2012},
 {'day': 3, 'month': 6, 'year': 2013},
 {'day': 20, 'month': 2, 'year': 2013},
 {'day': 20, 'month': 2, 'year': 2014},
 {'day': 31, 'month': 12, 'year': 2013},
 {'day': 19, 'month': 9, 'year': 2013},
 {'day': 25, 'month': 11, 'year': 2013},
 {'day': 14, 'month': 3, 'year': 2014},
 {'day': 12, 'month': 12, 'year': 2013},
 {'day': 31, 'month': 12, 'year': 2012},
 {'day': 18, 'month': 6, 'year': 2013},
 {'day': 19, 'month': 8, 'year': 2013},
 {'day': 14, 'month': 9, 'year': 2012},
 {'day': 30, 'month': 10, 'year': 2013},
 {'day': 3, 'month': 6, 'year': 2013},
 {'day': 3, 'month': 10, 'year': 2013},
 {'day': 31, 'month': 12, 'year': 2013},
 {'day': 12, 'month': 8, 'year': 2013},
 {'day': 2, 'month': 4, 'year': 2013},
 {'day': 4, 'month': 3, 'year': 2014},
 {'day': 25, 'month': 3, 'year': 2014},
 {'day': 3, 'month': 9, 'year': 2013},
 {'day': 12, 'month': 11, 'year': 2012},
 {'day': 21, 'month': 6, 'year': 2013},
 {'day': 12, 'month': 12, 'year': 2012},
 {'day': 5, 'month': 3, 'year': 2014},
 {'day': 29, 'month': 8, 'year': 2013},
 {'day': 18, 'month': 2, 'year': 2014},
 {'day': 19, 'month': 9, 'year': 2013},
 {'day': 29, 'month': 5, 'year': 2014},
 {'day': 3, 'month': 4, 'year': 2014},
 {'day': 10, 'month': 6, 'year': 2014},
 {'day': 2, 'month': 4, 'year': 2014},
 {'day': 31, 'month': 12, 'year': 2013},
 {'day': 24, 'month': 6, 'year': 2014},
 {'day': 2, 'month': 5, 'year': 2014},
 {'day': 10, 'month': 7, 'year': 2012},
 {'day': 13, 'month': 9, 'year': 2011},
 {'day': 28, 'month': 7, 'year': 2011},
 {'day': 15, 'month': 8, 'year': 2010},
 {'day': 19, 'month': 9, 'year': 2012},
 {'day': 25, 'month': 3, 'year': 2011},
 {'day': 1, 'month': 3, 'year': 2009},
 {'day': 28, 'month': 7, 'year': 2013},
 {'day': 5, 'month': 12, 'year': 2010},
 {'day': 12, 'month': 7, 'year': 2013},
 {'day': 1, 'month': 12, 'year': 2010}]


les auteurs de chaque livre notés dans des colonnes séparées sont : 
[{'author1': 'W. Frank Ableson',
  'author2': 'Charlie Collins',
  'author3': 'Robi Sen'},
 {'author1': 'W. Frank Ableson', 'author2': 'Robi Sen'},
 {'author1': 'Gojko Adzic'},
 {'author1': 'Tariq Ahmed',
  'author2': 'Dan Orlando',
  'author3': 'John C. Bland II'},
 {'author1': 'Tariq Ahmed with Jon Hirschi', 'author2': 'Faisal Abid'},
 {'author1': 'Satnam Alag'},
 {'author1': 'Bernerd Allmon', 'author2': 'Jeremy Anderson'},
 {'author1': 'Rob Allen', 'author2': 'Nick Lo', 'author3': 'Steven Brown'},
 {'author1': 'Andres Almiray', 'author2': 'Danno Ferrin', 'author3': ''},
 {'author1': 'Peter Armstrong'},
 {'author1': 'Alexandre de Castro Alves'},
 {'author1': 'Levi Asher', 'author2': 'Christian Crumlish'},
 {'author1': 'Peter Armstrong'},
 {'author1': 'Jamil Azher'},
 {'author1': 'Kyle Banker'},
 {'author1': 'Kyle Baley', 'author2': 'Donald Belcham'},
 {'author1': 'Michael Barlotta'},
 {'author1': 'Michael J. Barlotta', 'author2': 'Jason R. Weiss'},
 {'author1': 'Michael J. Barlotta'},
 {'author1': 'Christian Bauer', 'author2': 'Gavin King'},
 {'author1': 'Jon Barrilleaux'},
 {'author1': 'Christian Bauer', 'author2': 'Gavin King'},
 {'author1': 'Shawn Bayern'},
 {'author1': 'Clinton Begin',
  'author2': 'Brandon Goodin',
  'author3': 'Larry Meadors'},
 {'author1': 'Douglas W. Bennett'},
 {'author1': 'Emmanuel Bernard', 'author2': 'John Griffin'},
 {'author1': 'Bear Bibeault', 'author2': 'Yehuda Katz'},
 {'author1': 'Bear Bibeault', 'author2': 'Yehuda Katz'},
 {'author1': 'Kenneth P. Birman'},
 {'author1': 'David A. Black'},
 {'author1': 'David A. Black'},
 {'author1': 'Paul A. Boag'},
 {'author1': 'Daniele Bochicchio',
  'author2': 'Stefano Mostarda',
  'author3': ''},
 {'author1': 'Anthony Briggs'},
 {'author1': 'Richard Brooks'},
 {'author1': 'C. Wayne Brown', 'author2': 'Barry J. Shepherd'},
 {'author1': 'Margaret M. Burnett', 'author2': 'Adele Goldberg', 'author3': ''},
 {'author1': 'Bear P. Cahill'},
 {'author1': 'Christopher Allen', 'author2': 'Shannon Appelcline'},
 {'author1': 'Christian Bauer', 'author2': 'Gavin King'},
 {'author1': 'Chad A. Campbell', 'author2': 'John Stockton'},
 {'author1': 'Naomi R. Ceder'},
 {'author1': 'Tom Cervenka'},
 {'author1': 'William R. Cockayne and Michael Zyda', 'author2': 'editors'},
 {'author1': 'Arnaud Cogoluegnes',
  'author2': 'Thierry Templier',
  'author3': ''},
 {'author1': 'Rod Colledge'},
 {'author1': 'Charlie Collins', 'author2': 'Michael D. Galpin', 'author3': ''},
 {'author1': 'Damian Conway'},
 {'author1': 'Robert Cooper', 'author2': 'Charles Collins'},
 {'author1': 'Dave Crane', 'author2': 'Eric Pascarello with Darren James'},
 {'author1': 'Dave Crane',
  'author2': 'Jord Sonneveld and Bear Bibeault with Ted Goddard',
  'author3': 'Chris Gray'},
 {'author1': 'Dave Crane', 'author2': 'Bear Bibeault with Tom Locke'},
 {'author1': 'Chris Richardson'},
 {'author1': 'David Cross'},
 {'author1': 'Rob Crowther'},
 {'author1': 'Dan Allen'},
 {'author1': 'Martijn Dashorst', 'author2': 'Eelco Hillenius'},
 {'author1': 'Jeff Davis'},
 {'author1': 'Donald Brown', 'author2': 'Chad Michael Davis', 'author3': ''},
 {'author1': 'Tony DeLia',
  'author2': 'Galina Landres',
  'author3': 'Isidor Rivera'},
 {'author1': 'Alan Dennis'},
 {'author1': 'Robert Chapman'},
 {'author1': 'Hanumant Deshmukh', 'author2': 'Jignesh Malavia', 'author3': ''},
 {'author1': 'Ken Rimple', 'author2': 'Srini Penchikala'},
 {'author1': 'Jos Dirksen'},
 {'author1': 'Clayton Donley'},
 {'author1': 'David Dossot', 'author2': "John D'Emic"},
 {'author1': 'Dave Johnson'},
 {'author1': 'Stephen C. Drye', 'author2': 'William C. Wake'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Vikram Goyal'},
 {'author1': 'Fergal Grimes'},
 {'author1': 'John E. Grayson'},
 {'author1': 'Glen Smith', 'author2': 'Peter Ledbrook'},
 {'author1': 'Richard S. Hall',
  'author2': 'Karl Pauls',
  'author3': 'Stuart McCulloch'},
 {'author1': 'Steven Gutz'},
 {'author1': 'Robert Hanson', 'author2': 'Adam Tacy'},
 {'author1': 'Daryl Harms', 'author2': 'Kenneth McDonald'},
 {'author1': 'Yvonne M. Harryman'},
 {'author1': 'Erik Hatcher', 'author2': 'Otis Gospodnetic'},
 {'author1': 'Erik Hatcher', 'author2': 'Steve Loughran'},
 {'author1': 'Erik Hatcher', 'author2': 'Otis Gospodnetic', 'author3': ''},
 {'author1': 'Tim Hatton'},
 {'author1': 'Tim Hatton'},
 {'author1': 'Tim Hatton'},
 {'author1': 'Chris Hay', 'author2': 'Brian H. Prince'},
 {'author1': 'Kevin Hazzard', 'author2': 'Jason Bock'},
 {'author1': 'Vikas Hazrati', 'author2': 'Balaji D Loganathan'},
 {'author1': 'Stefan Hepper',
  'author2': 'Peter Fischer',
  'author3': 'Stephan Hesmer'},
 {'author1': 'Paul S. Hethmon'},
 {'author1': 'Jack Herrington'},
 {'author1': 'Michael Hüttermann'},
 {'author1': 'Merlin Hughes', 'author2': 'Michael Shoffner', 'author3': ''},
 {'author1': 'Ted N. Husted',
  'author2': 'Cedric Dumoulin',
  'author3': 'George Franciscus'},
 {'author1': 'Claus Ibsen', 'author2': 'Jonathan Anstey'},
 {'author1': 'Javid Jamae', 'author2': 'Peter Johnson'},
 {'author1': 'Grant S. Ingersoll',
  'author2': 'Thomas S. Morton',
  'author3': ''},
 {'author1': 'Tim Jenness', 'author2': 'Simon Cozens'},
 {'author1': 'Philipp K. Janert'},
 {'author1': 'Jocelyn Harrington',
  'author2': 'Brandon Trebitowski',
  'author3': 'Christopher Allen'},
 {'author1': 'Andrew L. Johnson'},
 {'author1': 'Don Jones'},
 {'author1': 'Robert I. Kabacoff'},
 {'author1': 'Matthias Kaeppler',
  'author2': 'Michael D. Galpin',
  'author3': 'Charlie Collins'},
 {'author1': 'Ramarao Kanneganti', 'author2': 'Prasad A. Chodavarapu'},
 {'author1': 'Ryan Bigg', 'author2': 'Yehuda Katz'},
 {'author1': 'Marcin Kawalerowicz', 'author2': 'Craig Berntson'},
 {'author1': 'Erik Keller'},
 {'author1': 'Kermit Project at Columbia University'},
 {'author1': 'Dierk Koenig with Andrew Glover',
  'author2': 'Paul King',
  'author3': 'Guillaume Laforge'},
 {'author1': 'Norman Klein', 'author2': 'Max Carlson with Glenn MacEwen'},
 {'author1': 'Timothy D. Korson', 'author2': 'Vijay K. Vaishnavi'},
 {'author1': 'Dierk König',
  'author2': 'Guillaume Laforge',
  'author3': 'Paul King'},
 {'author1': 'Lasse Koskela'},
 {'author1': 'Lasse Koskela'},
 {'author1': 'Peter J. Kovach'},
 {'author1': 'Kenneth A. Kousen'},
 {'author1': 'Benjamin L. Kovitz'},
 {'author1': 'Pierre Henri Kuate',
  'author2': 'Tobin Harris',
  'author3': 'Christian Bauer'},
 {'author1': 'Ramnivas Laddad'},
 {'author1': 'Teo Lachev'},
 {'author1': 'Ramnivas Laddad'},
 {'author1': 'Chuck Lam'},
 {'author1': 'Galina', 'author2': 'Vlad Landres'},
 {'author1': 'Galina Landres', 'author2': 'Vlad Landres'},
 {'author1': 'Amanda Laucher'},
 {'author1': 'Simon Laws',
  'author2': 'Mark Combellack',
  'author3': 'Raymond Feng'},
 {'author1': 'Compiled', 'author2': 'introduced by Ted Lewis'},
 {'author1': 'Ted Lewis', 'author2': 'friends'},
 {'author1': 'Howard M. Lewis Ship'},
 {'author1': 'Patrick Lightbody', 'author2': 'Jason Carreira'},
 {'author1': 'Brendan G. Lim with Jerry Cheung', 'author2': 'Jeremy McAnally'},
 {'author1': 'Martin Logan', 'author2': 'Eric Merritt', 'author3': ''},
 {'author1': 'Brett Lonsdale', 'author2': 'Nick Swan'},
 {'author1': 'Harold Lorin'},
 {'author1': 'Joey Lott', 'author2': 'Kathryn Rotondo', 'author3': 'Sam Ahn'},
 {'author1': 'Steve Loughran', 'author2': 'Erik Hatcher'},
 {'author1': 'Jerome Louvel', 'author2': 'Thierry Boileau', 'author3': ''},
 {'author1': 'Bruno Lowagie'},
 {'author1': 'Bruno Lowagie'},
 {'author1': 'Kyle Lussier'},
 {'author1': 'Jeffrey Machols'},
 {'author1': 'Daniel C. Lynch',
  'author2': 'James P. Gray',
  'author3': 'and Edward Rabinovitch'},
 {'author1': 'Tim Maher'},
 {'author1': 'Gary Scott Malkin'},
 {'author1': 'Qusay H. Mahmoud'},
 {'author1': 'Kito D. Mann'},
 {'author1': 'Fabrice Marguerie',
  'author2': 'Steve Eichert',
  'author3': 'Jim Wooley'},
 {'author1': 'Richard Scott Mark'},
 {'author1': 'Haralambos Marmanis', 'author2': 'Dmitry Babenko'},
 {'author1': 'Vincent Massol with Ted Husted'},
 {'author1': 'Chris A. Mattmann', 'author2': 'Jukka L. Zitting'},
 {'author1': 'Joe McGinn'},
 {'author1': 'Jeremy McAnally', 'author2': 'Assaf Arkin'},
 {'author1': 'Paul Messick'},
 {'author1': 'Daniel Minoli', 'author2': 'Andrew Schmidt'},
 {'author1': 'Daniel Minoli', 'author2': 'Thomas W. Golway', 'author3': ''},
 {'author1': 'Simon Morris'},
 {'author1': 'Stefano Mostarda', 'author2': 'Marco De Sanctis', 'author3': ''},
 {'author1': 'Wynn Netherland',
  'author2': 'Nathan Weizenbaum',
  'author3': 'Chris Eppstein'},
 {'author1': 'Darren Neimke'},
 {'author1': 'Ted Neward'},
 {'author1': 'Ted Neward'},
 {'author1': 'Ted Neward'},
 {'author1': 'Contributions from 53 SQL Server MVPs',
  'author2': 'Edited by Paul Nielsen',
  'author3': 'Kalen Delaney'},
 {'author1': 'Contributions from 53 SQL Server MVPs; Edited by Paul Nielsen',
  'author2': 'Kalen Delaney',
  'author3': 'Greg Low'},
 {'author1': 'Paul Nielsen', 'author2': 'Kalen Delaney', 'author3': 'Greg Low'},
 {'author1': 'Regina O. Obe', 'author2': 'Leo S. Hsu'},
 {'author1': "Kevin O'Malley"},
 {'author1': 'Roy Osherove'},
 {'author1': 'Sean Owen', 'author2': 'Robin Anil', 'author3': 'Ted Dunning'},
 {'author1': 'Jeffrey Palermo', 'author2': 'Ben Scheirman', 'author3': ''},
 {'author1': 'Jeffrey Palermo',
  'author2': 'Ben Scheirman',
  'author3': 'Jimmy Bogard'},
 {'author1': 'Jeffrey Palermo',
  'author2': 'Jimmy Bogard',
  'author3': 'Eric Hexter'},
 {'author1': 'Debu Panda', 'author2': 'Reza Rahman', 'author3': 'Ryan Cuprak'},
 {'author1': 'Debu Panda', 'author2': 'Reza Rahman', 'author3': 'Derek Lane'},
 {'author1': 'Anthony Patton'},
 {'author1': 'Thomas B. Passin'},
 {'author1': 'Anthony Patton'},
 {'author1': 'Bruce Payette'},
 {'author1': 'Bruce Payette'},
 {'author1': 'Pete Brown'},
 {'author1': 'Pete Brown'},
 {'author1': 'Patrick Peak', 'author2': 'Nick Heudecker'},
 {'author1': 'Matt Pearson'},
 {'author1': 'Timothy Binkley-Jones',
  'author2': 'Massimo Perga',
  'author3': ''},
 {'author1': 'Timothy Perrett'},
 {'author1': 'Theo Petersen'},
 {'author1': 'Tomas Petricek with Jon Skeet'},
 {'author1': 'Dhanji R. Prasanna'},
 {'author1': 'Peter Harrington'},
 {'author1': 'Eric Pulier and Hugh Taylor',
  'author2': 'Foreword by Paul Gaffney'},
 {'author1': 'Tijs Rademakers', 'author2': 'Jos Dirksen'},
 {'author1': 'Tijs Rademakers'},
 {'author1': 'J. B. Rainsberger with contributions by Scott Stirling'},
 {'author1': 'Oren Eini writing as Ayende Rahien'},
 {'author1': 'Noel Rappin', 'author2': 'Robin Dunn'},
 {'author1': 'Nilanjan Raychaudhuri'},
 {'author1': 'Amit Rathore'},
 {'author1': 'Trygve Reenskaug'},
 {'author1': 'Dagfinn Reiersøl with Marcus Baker', 'author2': 'Chris Shiflett'},
 {'author1': 'John Resig'},
 {'author1': 'Ronny Richardson'},
 {'author1': 'Matthew Robinson', 'author2': 'Pavel Vorobiev'},
 {'author1': 'Lawrence H. Rodrigues'},
 {'author1': 'Evan Rosen'},
 {},
 {'author1': 'Jothy Rosenberg', 'author2': 'Arthur Mateos'},
 {'author1': 'Michael Rosing'},
 {'author1': 'Warren D. Sande', 'author2': 'Carter Sande'},
 {'author1': 'Paul Sanghera'},
 {'author1': 'Arnon Rotem-Gal-Oz'},
 {'author1': 'Ashish Sarin'},
 {'author1': 'Matthew Scarpino',
  'author2': 'Stephen Holder',
  'author3': 'Stanford Ng'},
 {'author1': 'Matthew Scarpino'},
 {'author1': 'Andrew Schmidt', 'author2': 'Daniel Minoli'},
 {'author1': 'Mark Seemann'},
 {'author1': 'Richard Sezov', 'author2': 'Jr'},
 {'author1': 'Daniel Selman'},
 {'author1': 'Gal Shachor', 'author2': 'Adam Chace', 'author3': 'Magnus Rydin'},
 {'author1': 'Iain Shigeoka'},
 {'author1': 'Ronny Richardson',
  'author2': 'Michael Shoffner',
  'author3': 'Marq Singer'},
 {'author1': 'Richard Siddaway'},
 {'author1': 'Richard Siddaway'},
 {'author1': 'Bruce Simpson',
  'author2': 'John Mitchell',
  'author3': 'Brian Christeson'},
 {'author1': 'Nishant Sivakumar'},
 {'author1': 'Jon Skeet'},
 {'author1': 'Jon Skeet'},
 {'author1': 'Peter Small'},
 {'author1': 'Greg Smith', 'author2': 'Ahmed Sidky'},
 {'author1': 'Early Stephens'},
 {'author1': 'Bruce Snyder', 'author2': 'Dejan Bosanac', 'author3': ''},
 {'author1': 'Ian W. Stirk'},
 {'author1': 'Joshua D. Suereth'},
 {'author1': 'Benjamin G. Sullins', 'author2': 'Mark B. Whipple'},
 {'author1': 'Adam Tacy',
  'author2': 'Robert Hanson',
  'author3': 'Jason Essington'},
 {'author1': 'Benjamin G. Sullins', 'author2': 'Mark B. Whipple'},
 {'author1': 'Petar Tahchiev',
  'author2': 'Felipe Leme',
  'author3': 'Vincent Massol'},
 {'author1': 'Bruce A. Tate'},
 {'author1': 'Bruce Tate', 'author2': 'Mike Clark', 'author3': 'Bob Lee'},
 {'author1': 'Arnaud Cogoluegnes',
  'author2': 'Thierry Templier',
  'author3': 'Gary Gregory'},
 {'author1': 'Gregory M. Travis'},
 {'author1': 'Brandon Trebitowski',
  'author2': 'Christopher Allen',
  'author3': ''},
 {'author1': 'Bret Updegraff'},
 {'author1': 'JD "Illiad" Frazer'},
 {'author1': 'Alvaro Videla', 'author2': 'Jason J.W. Williams'},
 {'author1': 'Martien Verbruggen'},
 {'author1': 'Craig Walls', 'author2': 'Norman Richards'},
 {'author1': 'Craig Walls', 'author2': 'Ryan Breidenbach'},
 {'author1': 'Craig Walls with Ryan Breidenbach'},
 {'author1': 'Willie Wheeler with Joshua White'},
 {'author1': 'Craig Walls'},
 {'author1': 'James P. White', 'author2': 'David A. Hemphill'},
 {'author1': 'Phil Wicklund'},
 {'author1': 'Wictor Wilén'},
 {'author1': 'Alan R. Williamson'},
 {'author1': 'Anthony Williams'},
 {'author1': 'Mark Wilson', 'author2': 'Tracey Wilson'},
 {'author1': 'Noel Yuhanna'},
 {'author1': 'Gabe Zichermann', 'author2': 'Chris Cunningham'},
 {'author1': 'Holly Cummins', 'author2': 'Timothy Ward'},
 {'author1': 'Jesus Garcia', 'author2': 'Grgur Grisogono', 'author3': ''},
 {'author1': 'W. Frank Ableson',
  'author2': 'Robi Sen',
  'author3': 'Chris King'},
 {'author1': 'Martin Evans', 'author2': 'Joshua Noble', 'author3': ''},
 {'author1': 'Mike Cantelon',
  'author2': 'Marc Harter',
  'author3': 'T.J. Holowaychuk'},
 {'author1': 'Matthew E. Hodges'},
 {'author1': 'Ben Vinegar', 'author2': 'Anton Kovalyov'},
 {'author1': 'Duane K. Fields', 'author2': 'Mark A. Kolb'},
 {'author1': 'Steven J. Gutz'},
 {'author1': 'Maria Winslow'},
 {'author1': 'Steven J. Gutz'},
 {'author1': 'Ajamu A. Wesley'},
 {},
 {},
 {},
 {'author1': 'Bruce Trask', 'author2': 'Angel Roman'},
 {'author1': 'Nathan Marz', 'author2': 'James Warren'},
 {'author1': 'Patrick Lee'},
 {'author1': 'Hanumant Deshmukh', 'author2': 'Jignesh Malavia'},
 {'author1': 'Kalen Delaney',
  'author2': 'Louis Davidson',
  'author3': 'Greg Low'},
 {'author1': 'Christian Bauer', 'author2': 'Gavin King', 'author3': ''},
 {'author1': 'Rob Crowther', 'author2': 'Joe Lennon', 'author3': 'Ash Blue'},
 {'author1': 'Alex Holmes'},
 {'author1': 'Jonathan Campos'},
 {'author1': 'Nicholas Dimiduk', 'author2': 'Amandeep Khurana'},
 {'author1': 'Jim Jackson', 'author2': 'II', 'author3': 'Ian Gilman'},
 {'author1': 'Carlos M. Sessa'},
 {'author1': 'Don Jones', 'author2': 'Richard Siddaway', 'author3': ''},
 {'author1': 'Julio C. Ody'},
 {'author1': 'Robert A. Rice Jr.'},
 {'author1': 'David Dossot', 'author2': "John D'Emic", 'author3': ''},
 {'author1': 'David Wood', 'author2': 'Marsha Zaidman', 'author3': 'Luke Ruth'},
 {'author1': 'Michael S. Mikowski', 'author2': 'Josh C. Powell'},
 {'author1': 'Roy Osherove'},
 {'author1': 'Nicolas Leroux', 'author2': 'Sietse de Kaper'},
 {'author1': 'Warren Sande', 'author2': 'Carter Sande'},
 {'author1': 'Chris Buckett'},
 {'author1': 'Josiah Carlson'},
 {'author1': 'Christopher R. Mitchell'},
 {'author1': 'Jonas Partner', 'author2': 'Aleksa Vukotic', 'author3': ''},
 {'author1': 'Christopher R. Mitchell'},
 {'author1': 'Paul Chiusano', 'author2': 'Rúnar Bjarnason'},
 {'author1': 'Alex Young', 'author2': 'Marc Harter'},
 {'author1': 'G. Ann Campbell', 'author2': 'Patroklos P. Papapetrou'},
 {'author1': 'Peter M. Brown'},
 {'author1': 'Peter Hilton', 'author2': 'Erik Bakker', 'author3': ''},
 {'author1': 'Jason C. Helmick'},
 {'author1': 'William Back', 'author2': 'Nicholas Goodman', 'author3': ''},
 {'author1': 'Gavin M. Roy'},
 {'author1': 'Raymond Roestenburg',
  'author2': 'Rob Bakker',
  'author3': 'Rob Williams'},
 {'author1': 'Keith B. Wood'},
 {'author1': 'Mala Gupta'},
 {'author1': 'Marcus Hammarberg', 'author2': 'Joakim Sunden'},
 {'author1': 'Trey Grainger', 'author2': 'Timothy Potter'},
 {'author1': 'MIchael Barlotta'},
 {'author1': 'Glen Smith', 'author2': 'Peter Ledbrook'},
 {'author1': 'Ryan Bigg',
  'author2': 'Yehuda Katz',
  'author3': 'and Steve Klabnik'},
 {'author1': 'Daniel G. McCreary', 'author2': 'Ann M. Kelly'},
 {'author1': 'Don Jones', 'author2': 'Jeffery D. Hicks'},
 {'author1': 'Matthew D. Groves'},
 {'author1': 'Don Jones', 'author2': 'Jeffery Hicks'},
 {'author1': 'Florian Müller', 'author2': 'Jay Brown', 'author3': 'Jeff Potts'},
 {'author1': 'Paul Messick'},
 {'author1': 'Craig Walls'},
 {'author1': 'Richard Siddaway'},
 {'author1': 'Ola Ellnestam', 'author2': 'Daniel Brolund'},
 {'author1': 'Matthew Carver'},
 {'author1': 'Dean Alan Hume'},
 {'author1': 'Joshua Suereth', 'author2': 'Matthew Farwell'},
 {'author1': 'Edited by Jeffery Hicks',
  'author2': 'Richard Siddaway',
  'author3': 'Oisin Grehan'},
 {'author1': 'Ivan Porto Carrero',
  'author2': 'Ross A. Baker',
  'author3': 'Dave Hrycyszyn'},
 {'author1': 'Benjamin Muschko'},
 {'author1': 'Brian Ford', 'author2': 'Lukas Ruebbelke'},
 {'author1': 'David Nicolette'},
 {'author1': 'Tomas Petricek', 'author2': 'Phillip Trelford'},
 {'author1': 'Jon Skeet'},
 {'author1': 'Regina Obe', 'author2': 'Leo Hsu'},
 {'author1': 'Robert Kabacoff'},
 {'author1': 'Michael Fogus', 'author2': 'Chris Houser'},
 {'author1': 'Brendan G. Lim', 'author2': 'Martin Conte Mac Donell'},
 {'author1': 'Joachim Haagen Skeie'},
 {'author1': 'Norman Maurer', 'author2': 'Courtney Robinson'},
 {'author1': 'Itamar Syn-Hershko'},
 {'author1': 'Paula Beer', 'author2': 'Carl Simmons'},
 {'author1': 'Mala Gupta'},
 {'author1': 'Samuel M. Breed', 'author2': 'Cole Krumbholz', 'author3': ''},
 {'author1': 'Amit Rathore'},
 {},
 {'author1': 'Rene Rubalcava'},
 {'author1': 'Nina Zumel', 'author2': 'John Mount'},
 {'author1': 'Radu Gheorghe', 'author2': 'Matthew Lee Hinman'},
 {'author1': 'James Bannan'},
 {'author1': 'John F. Smart'},
 {'author1': 'Ajay Kapur',
  'author2': 'Perry Cook',
  'author3': 'Spencer Salazar'},
 {'author1': 'Ricardo Alcocer'},
 {'author1': 'Timothy Binkley-Jones',
  'author2': 'Massimo Perga',
  'author3': 'Michael Sync'},
 {'author1': 'Claudio Martella', 'author2': 'Roman Shaposhnik', 'author3': ''},
 {'author1': 'Brian Ketelsen', 'author2': 'Erik St. Martin', 'author3': ''},
 {'author1': 'David A. Black'},
 {'author1': 'Randy Abernethy'},
 {'author1': 'Aslam Khan'},
 {'author1': 'Roland Kuhn', 'author2': 'Jamie Allen'},
 {'author1': 'Sean Allen', 'author2': 'Peter Pathirana', 'author3': ''},
 {'author1': 'Monsur Hossain'},
 {'author1': 'Theodore J. (T.J.) VanToll III'},
 {'author1': 'Henrik Brink', 'author2': 'Joseph Richards'},
 {'author1': 'Nicolas G. Bevacqua'},
 {'author1': 'Chris Buckett'},
 {'author1': 'Mike McQuaid'},
 {'author1': 'Richard L. Saltzer', 'author2': 'Istvan Szegedi'},
 {'author1': 'Raoul-Gabriel Urma', 'author2': 'Mario Fusco', 'author3': ''},
 {'author1': 'Kyle Banker',
  'author2': 'Peter Bakkum',
  'author3': 'Tim Hawkins'},
 {'author1': 'Simon Holmes'},
 {'author1': 'Bear Bibeault', 'author2': 'Yehuda Katz', 'author3': ''},
 {'author1': 'Saša Juric´'},
 {'author1': 'Elijah Meeks'},
 {'author1': 'Don Jones'},
 {'author1': 'Chris Garrard'},
 {'author1': 'Oliver Drobnik'},
 {'author1': 'Dimitri Aivaliotis'},
 {'author1': 'Alex Holmes'},
 {'author1': 'Bradley Austin Davis', 'author2': 'Karen Bryla', 'author3': ''},
 {'author1': 'Cody Bumgardner'},
 {'author1': 'Avi Pfeffer'},
 {'author1': 'Joseph Hocking'},
 {'author1': 'Evan M. Hahn'},
 {'author1': 'Rick Umali'},
 {'author1': 'Don Jones', 'author2': 'Jeffery Hicks', 'author3': ''},
 {'author1': 'Emmit A. Scott', 'author2': 'Jr.'},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {},
 {}]


le nombre de livres écrit par auteurs notés en premier dans la liste est :
[{'_id': None, 'nb': 37},
 {'_id': 'Vikram Goyal', 'nb': 12},
 {'_id': 'Don Jones', 'nb': 6},
 {'_id': 'Christian Bauer', 'nb': 4},
 {'_id': 'Craig Walls', 'nb': 4},
 {'_id': 'Dave Crane', 'nb': 3},
 {'_id': 'Tim Hatton', 'nb': 3},
 {'_id': 'Jeffrey Palermo', 'nb': 3},
 {'_id': 'Erik Hatcher', 'nb': 3},
 {'_id': 'Bear Bibeault', 'nb': 3}]


la distribution du nombre d'auteurs est :
[{'nb_auteur': 431}]
